config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  get  'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	validates :description, presence: true 

	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
 class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
  				:rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

    before_filter :authenticate_user!, except: []

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update

    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy

  @pin = current_user.pins.find(params[:id])
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>
		by <%= link_to "Mattan Griffel", "http://mattangriffel.com"%>

	</small>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<head>
			  <title>One Month Rails</title>
			  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
			  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			  <%= csrf_meta_tags %>
			  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>

		</head>
		<body>
			<%= render 'layouts/header' %>

			<div class="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
					<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>
			 
		</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach 
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
	in one month. This is the sample application
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h1>You're logged in!</h1>  
<% else %>
<div class="jumbotron">
  <h1>Welcome to One Month Rails!</h1>
  <p>
    You've found
   the home page for the
    <%= link_to "One Month Rails", "http://onemonthrails.com"%>
    application.
  </p>
  <p> 
    <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
  </p>
</div>

<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<tr>
  <td><%= pin.description %></td>
  <td><%= link_to 'Show', pin %></td>
  <% if current_user == pin.user %>
  <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
  <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  <% end %>
</tr>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<br></br>
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @pins%>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<div class="well">
  	<p>
		  <%= @pin.description %>
		</p>
		<p>
		  <%= @pin.user.name %>
		</p>
		<% if current_user ==@pin.user %>
			<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
		<%= link_to 'Back', pins_path %>
		</div>
  </div>
</div>